Add region to Deployment step

diff --git a/.github/workflows/dev-main-pipeline.yaml b/.github/workflows/dev-main-pipeline.yaml
--- a/.github/workflows/dev-main-pipeline.yaml
+++ b/.github/workflows/dev-main-pipeline.yaml
@@ -91,6 +91,20 @@ jobs:
         echo "Tests failed. Check test results for details."
         exit 1
 
+    # - name: Scan for Vulnerabilities # Scans the code's dependencies for 'High Level' vulnerabilities.
+    #   uses: snyk/actions/dotnet-core@master
+    #   with:
+    #     command: test
+    #     args: '--severity-threshold=high'
+    #     snyk_token: ${{ secrets.SNYK_TOKEN }}
+    #   continue-on-error: true
+    #   id: security-scan
+    # - name: Check Security Scan Status # Outputs a message to the console if high level vulnerabilities are discovered in the dependencies.
+    #   if: steps.security-scan.outcome == 'failure'
+    #   run: |
+    #     echo "Security vulnerabilities detected. Review and address them before deploying."
+    #     exit 1
+
     - name: Publish Application # Prepares the application for deployment by adding all of its files and dependencies to a folder.
       run: dotnet publish -c Release -o ./publish
       continue-on-error: true
@@ -119,6 +133,7 @@ jobs:
         application_name: FairwayManager2
         environment_name: FairwayManager2-env
         version_label: prod-${{ github.run_number }}
+        region: ${{ secrets.AWS_REGION }}
         deployment_package: deploy.zip
       continue-on-error: true
       id: deploy
